### ISSUE TITLE
Adapt docker-java to unix-socket thanks to jnr-unix-socket

### ISSUE THREAD

**Issue by ghost** [kpelykh/docker-java#13] opened 2013-12-04 10:49 UTC
I think it can ba valuable to be able to read docker in java via unix socket as well.
It let us more easily continue to give rights on clients.

This project has a very good support for unix socket domain in mail unixes
https://github.com/jnr/jnr-unixsocket

**Comment by frankscholten** [comment] 2013-12-20 15:23
I did a quick experiment on my unixsocket branch: https://github.com/frankscholten/docker-java/commit/a19aa436da8b1bfe937d68ea08b9f18d99702ac4, seems to work.

@kametic Care to join in?

**Comment by kametic** [comment] 2013-12-20 15:32
hi @frankscholten . Great to see that this is working. I will be happy to help. 

Since I'm completly new to docker internals but I know java well and a little of go, how can I help ? I've docker 0.7.2 installed .

**Comment by kpelykh** [comment] 2013-12-20 19:47
@frankscholten Does it work for you? Will you be able to provide a pull request to add support for sockets to the java-docker?

**Comment by frankscholten** [comment] 2013-12-23 10:41
@kpelykh @kametic In my pull request I only verified that sending the string "GET /images/json?all=0 HTTP/1.1\n\n" through the UnixSocketAddress gets a correct response back from Docker. What we have to do now is add code to translate the ClientRequest into a string representation and put it into the UnixSocketAddress, along with buffering and exception handling and read the response, also with buffering and exception handling. @kpelykh You are probably more familiar with the Jersey API than I am so could you add a code snippet for that? I love to continue working on it after that, just need a way to start.

**Comment by frankscholten** [comment] 2013-12-23 17:11
I figured out how to write the request into a buffer and created implementations for both the input and output buffers that use the UnixSocketChannel. The socket communication works but I now get exceptions about deserializing the JSON responses into Java classses. See this commit: https://github.com/frankscholten/docker-java/commit/02ec81c63ca4ca08d5fb281286ef9e052ff0ef94 @kpelykh Any ideas?

**Comment by dkatona** [comment] 2014-01-03 12:39
@frankscholten I think the problem is that DefaultHttpResponseParser just parses head, not message body - try calling response.getEntity() - it is null. When you upgrade to 4.3.1 version of http-core, you won't have to write your own classes for input and output buffers - there are SessionOutputBufferImpl/SessionInputBufferImpl implementations. But this won't help - it seems that DefaultHttpResponseParser needs to be adjusted, I've tried it, but no luck so far...

**Comment by kpelykh** [comment] 2014-01-10 00:14
@dkatona @frankscholten yeah that seems to be a problem. Message body is not getting parsed. in case of AbstractHttpClientConnection, body parsing happens in response = doReceiveResponse(request, conn, context); 

I'm merging commits into master branch and will try to resolve this issue with message body not being parsed.

**Comment by etux** [comment] 2014-03-07 08:19
Is there any intention to pick this up and include it in a short term release? what is the status?

**Comment by marcuslinke** [comment] 2014-06-17 10:13
Closed as project moved to https://github.com/docker-java/docker-java. Please check if that issue still persist and reissue there if necessary.

**Closed as completed by marcuslinke** 2014-06-17 10:13 UTC
